name: carson-bot

type: php:8.2

runtime:
    extensions:
        - apcu
        - mbstring
        - pdo_pgsql

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 2048

#variables:
#    php:
#        opcache.preload: /app/config/preload.php

mounts:
    '/var': { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)
    deploy: |
        set -x -e
        (>&2 symfony-deploy)

crons:
    run_tasks:
        spec: '*/5 * * * *'
        cmd: croncape bin/console app:task:run

    stale_issues_symfony:
        spec: '58 12 * * *'
        cmd: croncape bin/console app:issue:ping-stale symfony/symfony --not-updated-for 6months

    stale_issues_docs:
        spec: '48 12 * * *'
        cmd: croncape bin/console app:issue:ping-stale symfony/symfony-docs --not-updated-for 12months

    stale_issues_ux:
        spec: '38 12 * * *'
        cmd: croncape bin/console app:issue:ping-stale symfony/ux --not-updated-for 6months

relationships:
    database: "mydatabase:postgresql"




