name: carson-bot

type: php:7.2

runtime:
    extensions:
        - apcu
        - mbstring
        - iconv
        - ctype

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 2048

mounts:
    "var/cache": { source: local, source_path: "var/cache" }
    "var/logs": { source: local, source_path: "var/logs" }

hooks:
    build: |
        set -x -e

        APP_ENV=prod composer install --prefer-dist --optimize-autoloader --classmap-authoritative --no-progress --no-ansi --no-interaction --no-dev
        (>&2 SYMFONY_ENV=prod bin/console cache:clear --no-warmup)
        (>&2 SYMFONY_ENV=prod bin/console cache:warmup)

        # Keep the cache in a persistent directory
        # If your cache can be read-only, you can skip this step
        (>&2 mkdir -p tmp/cache && mv var/cache/prod tmp/cache/)

    deploy: |
        set -x -e

        # "install" cache
        # If your cache can be read-only, you can skip these steps
        rm -rf var/cache/prod
        cp -Rp tmp/cache/prod var/cache/
