# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.github.client:
        class: Github\Client
        arguments: []
        calls:
            - method: authenticate
              arguments:
                - http_token
                - %github_token%

    app.github.issues_api:
        class: Github\Api\Issue
        factory: ['@app.github.client', api]
        arguments: [issue]

    app.github.labels_api:
        class: Github\Api\Issue\Labels
        factory: ['@app.github.issues_api', labels]

    app.github.cached_labels_api:
        class: AppBundle\Issues\GitHub\CachedLabelsApi
        arguments: ['@app.github.labels_api', '%default_repository%']

    app.status_api.default:
        class: AppBundle\Issues\GitHub\GitHubStatusApi
        arguments: ['@app.github.cached_labels_api', '%default_repository%']

    app.github.request_handler:
        class: AppBundle\Issues\GitHubRequestHandler
        arguments: ['@app.github.labels_api', '@event_dispatcher', '%repositories%']

    app.github.exception_listener:
        class: Appbundle\Listener\GitHubExceptionListener
        arguments: ['%kernel.debug%']
        tags:
            - { name: kernel.event_subscriber }
