parameters:
    repositories:
        symfony/symfony:
            subscribers:
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelFromContentSubscriber'
                - 'App\Subscriber\MilestoneNewPRSubscriber'
                - 'App\Subscriber\WelcomeFirstTimeContributorSubscriber'
            secret: '%env(SYMFONY_SECRET)%'

        symfony/symfony-docs:
            subscribers:
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeOnPushSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelFromContentSubscriber'
                - 'App\Subscriber\MilestoneNewPRSubscriber'
                - 'App\Subscriber\WelcomeFirstTimeContributorSubscriber'
            secret: '%env(SYMFONY_DOCS_SECRET)%'

        # used in a functional test
        carsonbot-playground/symfony:
            subscribers:
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeOnPushSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelFromContentSubscriber'
                - 'App\Subscriber\MilestoneNewPRSubscriber'
                - 'App\Subscriber\WelcomeFirstTimeContributorSubscriber'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Subscriber,Kernel.php,GitHubEvents.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Subscriber\:
        resource: '../src/Subscriber/*'
        autoconfigure: false

    Github\Api\Issue:
        factory: ['@Github\Client', api]
        arguments: [issue]

    Github\Api\Issue\Labels:
        factory: ['@Github\Api\Issue', labels]

    Github\Api\Issue\Milestones:
        factory: ['@Github\Api\Issue', milestones]

    Github\Api\Issue\Comments:
        factory: ['@Github\Api\Issue', comments]

    App\Issues\StatusApi: '@App\Issues\GitHub\GitHubStatusApi'
    App\Issues\CommentsApiInterface: '@App\Issues\GitHub\GithubCommentsApi'

    App\Repository\Provider\InMemoryRepositoryProvider:
        arguments: [ '%repositories%' ]

    App\Repository\Provider\RepositoryProviderInterface: '@App\Repository\Provider\InMemoryRepositoryProvider'
