parameters:
    repositories:
        symfony/symfony:
            subscribers:
                - 'App\Subscriber\AutoUpdateTitleWithLabelSubscriber'
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\FindReviewerSubscriber'
                - 'App\Subscriber\AutoLabelFromContentSubscriber'
                - 'App\Subscriber\MilestoneNewPRSubscriber'
                - 'App\Subscriber\MilestoneMergedPRSubscriber'
                - 'App\Subscriber\WelcomeFirstTimeContributorSubscriber'
                - 'App\Subscriber\CloseDraftPRSubscriber'
                - 'App\Subscriber\UnsupportedBranchSubscriber'
                - 'App\Subscriber\MismatchBranchDescriptionSubscriber'
                - 'App\Subscriber\RemoveStalledLabelOnCommentSubscriber'
                - 'App\Subscriber\RewriteUnwantedPhrasesSubscriber'
                - 'App\Subscriber\AllowEditFromMaintainerSubscriber'
                - 'App\Subscriber\ApproveCiForNonContributors'
            secret: '%env(SYMFONY_SECRET)%'

        symfony/symfony-docs:
            subscribers:
                - 'App\Subscriber\AutoUpdateTitleWithLabelSubscriber'
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeOnPushSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\MilestoneMergedPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelFromContentSubscriber'
                - 'App\Subscriber\UnsupportedBranchSubscriber'
                - 'subscriber.symfony_docs.milestone'
                - 'App\Subscriber\RemoveStalledLabelOnCommentSubscriber'
                - 'App\Subscriber\RewriteUnwantedPhrasesSubscriber'
                - 'App\Subscriber\UpdateMilestoneWhenLabeledWaitingCodeMergeSubscriber'
                - 'App\Subscriber\AllowEditFromMaintainerSubscriber'
                - 'App\Subscriber\ApproveCiForNonContributors'
            secret: '%env(SYMFONY_DOCS_SECRET)%'

        # used in a functional test
        carsonbot-playground/symfony:
            subscribers:
                - 'App\Subscriber\AutoUpdateTitleWithLabelSubscriber'
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeOnPushSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\FindReviewerSubscriber'
                - 'App\Subscriber\AutoLabelFromContentSubscriber'
                - 'App\Subscriber\MilestoneNewPRSubscriber'
                - 'App\Subscriber\MilestoneMergedPRSubscriber'
                - 'App\Subscriber\WelcomeFirstTimeContributorSubscriber'
                - 'App\Subscriber\CloseDraftPRSubscriber'
                - 'App\Subscriber\UnsupportedBranchSubscriber'
                - 'App\Subscriber\MismatchBranchDescriptionSubscriber'
                - 'App\Subscriber\RemoveStalledLabelOnCommentSubscriber'
                - 'App\Subscriber\RewriteUnwantedPhrasesSubscriber'
                - 'App\Subscriber\UpdateMilestoneWhenLabeledWaitingCodeMergeSubscriber'
                - 'App\Subscriber\AllowEditFromMaintainerSubscriber'
                - 'App\Subscriber\ApproveCiForNonContributors'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $botUsername: '%env(BOT_USERNAME)%'

    _instanceof:
        App\Service\TaskHandler\TaskHandlerInterface:
            tags: ['app.task_handlers']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Subscriber,Kernel.php,GitHubEvents.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Subscriber\:
        resource: '../src/Subscriber/*'
        autoconfigure: false

    App\Api\Issue\IssueApi: '@App\Api\Issue\GithubIssueApi'
    App\Api\Label\LabelApi: '@App\Api\Label\GithubLabelApi'
    App\Api\Milestone\MilestoneApi: '@App\Api\Milestone\GithubMilestoneApi'
    App\Api\PullRequest\PullRequestApi: '@App\Api\PullRequest\GithubPullRequestApi'
    App\Api\Status\StatusApi: '@App\Api\Status\GitHubStatusApi'
    App\Api\Workflow\WorkflowApi: '@App\Api\Workflow\GithubWorkflowApi'

    App\Service\RepositoryProvider:
        arguments: [ '%repositories%' ]

    subscriber.symfony_docs.milestone:
        class: App\Subscriber\MilestoneNewPRSubscriber
        arguments:
            $ignoreCurrentVersion: true

    App\Service\TaskRunner:
        arguments:
            $handlers: !tagged_iterator app.task_handlers
