name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 8.2
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-8.1-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-8.1-
            composer-${{ runner.os }}-
            composer-

      - name: Docker
        run: docker compose up -d

      - name: Download dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Setup database
        run: bin/console doctrine:schema:create

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Upload log file
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test.log
          path: var/log/test.log
          retention-days: 5
