name: Static analysis

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: phpstan:1.4.6, cs2pr

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: PHPStan
        run: phpstan analyze --no-progress --error-format=checkstyle | cs2pr

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: php-cs-fixer:3.6, cs2pr

      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

  psalm:
    name: Psalm
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
          tools: vimeo/psalm:4.22.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: Psalm
        run: psalm --no-progress --output-format=github
